// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CRM.Model
{
    public partial class CrmActivityFollower : BaseEntity
    {
        [PrimaryKey, NotNull]
        public string ActivityFollowerId { get; set; }
        public string EmpId { get; set; }
        public bool? IsCreateAct { get; set; }
        public bool? IsInactive { get; set; }
        public bool? IsDelete { get; set; }
        public string CreatedById { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedById { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ActivityId { get; set; }
    }
}