// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRM.Model
{
    public partial class SmEmployee : BaseEntity
    {
        [PrimaryKey, NotNull]
        public string EmpId { get; set; }

        public string UserId { get; set; }
        public string DeptId { get; set; }
        public string PositionId { get; set; }
        public string EmpGroupId { get; set; }
        public string EmpLeaderId { get; set; }
        public string TitleNameEnumId { get; set; }
        public string BloodGroupEnumId { get; set; }
        public string MilitaryEnumId { get; set; }
        public string MaritalEnumId { get; set; }
        public string GenderEnumId { get; set; }
        public string EmpTypeEnumId { get; set; }
        public string WorkStatusEnumId { get; set; }
        public string EmpNo { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpNickName { get; set; }
        public string EmpTaxId { get; set; }
        public DateTime? EmpBirthDate { get; set; }
        public byte? EmpAge { get; set; }
        public string EmpNationality { get; set; }
        public string EmpRace { get; set; }
        public string EmpReligion { get; set; }
        public string EmpProfileImg { get; set; }
        public string EmpSignerImg { get; set; }
        public DateTime? EmpStartWordDate { get; set; }
        public DateTime? EmpLeaveDate { get; set; }
        public byte? EmpWorkYear { get; set; }
        public byte? EmpWordMonth { get; set; }
        public string AddrLine { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string LineId { get; set; }
        public string Facebook { get; set; }
        public bool? IsDraft { get; set; }
        public bool? IsInactive { get; set; }
        public bool? IsDelete { get; set; }
        public string CreatedById { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedById { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}