// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CRM.Model
{
    public partial class SmEnum : BaseEntity
    {
        [PrimaryKey, NotNull]
        public string EnumId { get; set; }
        public string EnumTypeId { get; set; }
        public string EnumNo { get; set; }
        public string EnumName { get; set; }
        public string Remark { get; set; }
        public bool? IsDefault { get; set; }
        public bool? IsInactive { get; set; }
        public bool? IsDelete { get; set; }
        public string CreatedById { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedById { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}